# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'columnConfigBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(669, 81)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.columnNameLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.columnNameLabel.sizePolicy().hasHeightForWidth())
        self.columnNameLabel.setSizePolicy(sizePolicy)
        self.columnNameLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.columnNameLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.columnNameLabel.setObjectName("columnNameLabel")
        self.horizontalLayout.addWidget(self.columnNameLabel)
        self.columnShownCB = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.columnShownCB.sizePolicy().hasHeightForWidth())
        self.columnShownCB.setSizePolicy(sizePolicy)
        self.columnShownCB.setMinimumSize(QtCore.QSize(80, 0))
        self.columnShownCB.setMaximumSize(QtCore.QSize(80, 16777215))
        self.columnShownCB.setChecked(True)
        self.columnShownCB.setObjectName("columnShownCB")
        self.horizontalLayout.addWidget(self.columnShownCB)
        self.decimalDD = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decimalDD.sizePolicy().hasHeightForWidth())
        self.decimalDD.setSizePolicy(sizePolicy)
        self.decimalDD.setMinimumSize(QtCore.QSize(120, 0))
        self.decimalDD.setMaximumSize(QtCore.QSize(120, 16777215))
        self.decimalDD.setObjectName("decimalDD")
        self.decimalDD.addItem("")
        self.decimalDD.addItem("")
        self.decimalDD.addItem("")
        self.decimalDD.addItem("")
        self.decimalDD.addItem("")
        self.decimalDD.addItem("")
        self.horizontalLayout.addWidget(self.decimalDD)
        self.useKCB = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useKCB.sizePolicy().hasHeightForWidth())
        self.useKCB.setSizePolicy(sizePolicy)
        self.useKCB.setMinimumSize(QtCore.QSize(130, 0))
        self.useKCB.setMaximumSize(QtCore.QSize(130, 16777215))
        self.useKCB.setObjectName("useKCB")
        self.horizontalLayout.addWidget(self.useKCB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        self.decimalDD.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.columnNameLabel.setText(_translate("Form", "N/A"))
        self.columnShownCB.setText(_translate("Form", "Shown"))
        self.decimalDD.setItemText(0, _translate("Form", "0 Decimals"))
        self.decimalDD.setItemText(1, _translate("Form", "1 Decimal"))
        self.decimalDD.setItemText(2, _translate("Form", "2 Decimals"))
        self.decimalDD.setItemText(3, _translate("Form", "3 Decimals"))
        self.decimalDD.setItemText(4, _translate("Form", "4 Decimals"))
        self.decimalDD.setItemText(5, _translate("Form", "All Decimals"))
        self.useKCB.setText(_translate("Form", "Use \'k\' above 10000"))
