# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configWindowBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(630, 462)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.applyButton = QtWidgets.QPushButton(Form)
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout.addWidget(self.applyButton)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 610, 394))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.mainLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.mainLayout.setObjectName("mainLayout")
        self.generalSettingsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.generalSettingsLabel.setObjectName("generalSettingsLabel")
        self.mainLayout.addWidget(self.generalSettingsLabel)
        self.emptySpacerLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.emptySpacerLabel.setText("")
        self.emptySpacerLabel.setObjectName("emptySpacerLabel")
        self.mainLayout.addWidget(self.emptySpacerLabel)
        self.columnSettingsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.columnSettingsLabel.setObjectName("columnSettingsLabel")
        self.mainLayout.addWidget(self.columnSettingsLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Table config: N/A"))
        self.applyButton.setText(_translate("Form", "Apply Settings"))
        self.generalSettingsLabel.setText(_translate("Form", "General settings"))
        self.columnSettingsLabel.setText(_translate("Form", "Columns"))
