# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pandaTableBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(404, 771)
        Form.setMinimumSize(QtCore.QSize(270, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.queryWidget = QtWidgets.QWidget(self.widget)
        self.queryWidget.setStyleSheet("")
        self.queryWidget.setObjectName("queryWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.queryWidget)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.queryWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.queryEdit = QtWidgets.QLineEdit(self.queryWidget)
        self.queryEdit.setObjectName("queryEdit")
        self.verticalLayout_3.addWidget(self.queryEdit)
        self.queryLabel = QtWidgets.QLabel(self.queryWidget)
        self.queryLabel.setText("")
        self.queryLabel.setObjectName("queryLabel")
        self.verticalLayout_3.addWidget(self.queryLabel)
        self.verticalLayout_2.addWidget(self.queryWidget)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.configButton = QtWidgets.QToolButton(self.frame)
        self.configButton.setObjectName("configButton")
        self.horizontalLayout.addWidget(self.configButton)
        self.filterEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterEdit.sizePolicy().hasHeightForWidth())
        self.filterEdit.setSizePolicy(sizePolicy)
        self.filterEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.filterEdit.setObjectName("filterEdit")
        self.horizontalLayout.addWidget(self.filterEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame)
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setMinimumSectionSize(30)
        self.tableView.verticalHeader().setCascadingSectionResizes(False)
        self.tableView.verticalHeader().setDefaultSectionSize(45)
        self.tableView.verticalHeader().setMinimumSectionSize(42)
        self.verticalLayout_2.addWidget(self.tableView)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Filters: (temporary UI, uses pandas query syntax)"))
        self.configButton.setText(_translate("Form", "S"))
