# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientHeaderBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(862, 31)
        Form.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuFrame = QtWidgets.QWidget(Form)
        self.menuFrame.setObjectName("menuFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menuFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.menuFrame)
        self.progressBar.setMaximumSize(QtCore.QSize(400, 12))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.menuLabel = QtWidgets.QLabel(self.menuFrame)
        self.menuLabel.setWordWrap(True)
        self.menuLabel.setObjectName("menuLabel")
        self.horizontalLayout_2.addWidget(self.menuLabel)
        self.horizontalLayout.addWidget(self.menuFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.menuLabel.setText(_translate("Form", "N/A"))
