# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmWidgetBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirmWidget(object):
    def setupUi(self, confirmWidget):
        confirmWidget.setObjectName("confirmWidget")
        confirmWidget.resize(965, 171)
        confirmWidget.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(confirmWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(confirmWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(confirmWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.confirmButton = QtWidgets.QPushButton(self.frame_3)
        self.confirmButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_2.addWidget(self.confirmButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.clientBusyLabel = QtWidgets.QLabel(confirmWidget)
        self.clientBusyLabel.setStyleSheet("color: rgb(193, 0, 0);")
        self.clientBusyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clientBusyLabel.setObjectName("clientBusyLabel")
        self.verticalLayout_2.addWidget(self.clientBusyLabel)

        self.retranslateUi(confirmWidget)
        QtCore.QMetaObject.connectSlotsByName(confirmWidget)

    def retranslateUi(self, confirmWidget):
        _translate = QtCore.QCoreApplication.translate
        confirmWidget.setWindowTitle(_translate("confirmWidget", "Form"))
        self.label.setText(_translate("confirmWidget", "Yo if you click on this button stuff is bound to happen bro ! "))
        self.confirmButton.setText(_translate("confirmWidget", "Confirm"))
        self.clientBusyLabel.setText(_translate("confirmWidget", "The client is currently busy!"))
