# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listPeekBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(918, 132)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topFrame = QtWidgets.QFrame(Form)
        self.topFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listImage = QtWidgets.QLabel(self.topFrame)
        self.listImage.setMinimumSize(QtCore.QSize(50, 50))
        self.listImage.setMaximumSize(QtCore.QSize(50, 50))
        self.listImage.setText("")
        self.listImage.setPixmap(QtGui.QPixmap("../../000000.png"))
        self.listImage.setScaledContents(False)
        self.listImage.setObjectName("listImage")
        self.horizontalLayout.addWidget(self.listImage)
        self.label = QtWidgets.QLabel(self.topFrame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.editButton = QtWidgets.QPushButton(self.topFrame)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.topFrame)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.verticalLayout.addWidget(self.topFrame)
        self.infoLabel = QtWidgets.QLabel(Form)
        self.infoLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "N/A"))
        self.editButton.setText(_translate("Form", "Edit"))
        self.deleteButton.setText(_translate("Form", "Delete"))
        self.infoLabel.setText(_translate("Form", "N/A"))
