# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'itemInfoTableBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(752, 636)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleBlock = QtWidgets.QFrame(Form)
        self.titleBlock.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBlock.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBlock.setObjectName("titleBlock")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleBlock)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLineLeft = QtWidgets.QFrame(self.titleBlock)
        self.titleLineLeft.setFrameShape(QtWidgets.QFrame.HLine)
        self.titleLineLeft.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.titleLineLeft.setObjectName("titleLineLeft")
        self.horizontalLayout.addWidget(self.titleLineLeft)
        self.widgetTitle = QtWidgets.QLabel(self.titleBlock)
        self.widgetTitle.setObjectName("widgetTitle")
        self.horizontalLayout.addWidget(self.widgetTitle)
        self.titleLineRight = QtWidgets.QFrame(self.titleBlock)
        self.titleLineRight.setFrameShape(QtWidgets.QFrame.HLine)
        self.titleLineRight.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.titleLineRight.setObjectName("titleLineRight")
        self.horizontalLayout.addWidget(self.titleLineRight)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addWidget(self.titleBlock)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.widgetTitle.setText(_translate("Form", "Info"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Property"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Value"))
