# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'itemListBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1073, 742)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.leftLayout = QtWidgets.QVBoxLayout(self.frame)
        self.leftLayout.setObjectName("leftLayout")
        self.itemListTablePlaceholder = QtWidgets.QWidget(self.frame)
        self.itemListTablePlaceholder.setObjectName("itemListTablePlaceholder")
        self.leftLayout.addWidget(self.itemListTablePlaceholder)
        self.horizontalLayout.addWidget(self.frame)
        self.rightFrame = QtWidgets.QFrame(Form)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightFrame)
        self.rightLayout.setObjectName("rightLayout")
        self.itemPeekPlaceholder = QtWidgets.QWidget(self.rightFrame)
        self.itemPeekPlaceholder.setObjectName("itemPeekPlaceholder")
        self.rightLayout.addWidget(self.itemPeekPlaceholder)
        self.rightTabsWidget = QtWidgets.QTabWidget(self.rightFrame)
        self.rightTabsWidget.setObjectName("rightTabsWidget")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.infoLayout = QtWidgets.QVBoxLayout(self.info)
        self.infoLayout.setObjectName("infoLayout")
        self.rightTabsWidget.addTab(self.info, "")
        self.listings = QtWidgets.QWidget()
        self.listings.setObjectName("listings")
        self.listingsLayout = QtWidgets.QVBoxLayout(self.listings)
        self.listingsLayout.setObjectName("listingsLayout")
        self.rightTabsWidget.addTab(self.listings, "")
        self.craft = QtWidgets.QWidget()
        self.craft.setObjectName("craft")
        self.craftLayout = QtWidgets.QVBoxLayout(self.craft)
        self.craftLayout.setObjectName("craftLayout")
        self.rightTabsWidget.addTab(self.craft, "")
        self.flip = QtWidgets.QWidget()
        self.flip.setObjectName("flip")
        self.flipLayout = QtWidgets.QVBoxLayout(self.flip)
        self.flipLayout.setObjectName("flipLayout")
        self.rightTabsWidget.addTab(self.flip, "")
        self.rightLayout.addWidget(self.rightTabsWidget)
        self.horizontalLayout.addWidget(self.rightFrame)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Form)
        self.rightTabsWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.rightTabsWidget.setTabText(self.rightTabsWidget.indexOf(self.info), _translate("Form", "Info"))
        self.rightTabsWidget.setTabText(self.rightTabsWidget.indexOf(self.listings), _translate("Form", "Listings"))
        self.rightTabsWidget.setTabText(self.rightTabsWidget.indexOf(self.craft), _translate("Form", "Craft"))
        self.rightTabsWidget.setTabText(self.rightTabsWidget.indexOf(self.flip), _translate("Form", "Flip"))
